# Generated by Django 3.0 on 2019-12-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeBox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='recipeBox.Recipe'),
        ),
    ]
